export const UPDATE_LINES = 'UPDATE_LINES';
export const UPDATE_CURRENT_LINE_NUMBER = 'UPDATE_CURRENT_LINE_NUMBER';
export const UPDATE_CURRENT_LINE_TEXT = 'UPDATE_CURRENT_LINE_TEXT';
export const UPDATE_LINE_TEXT = 'UPDATE_LINE_TEXT';
export const UPDATE_LINE_TYPE = 'UPDATE_LINE_TYPE';